config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #if logged in, root is home page
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  #otherwise root is login page
  root to: redirect('/users/sign_in')

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'registration/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'registration/:id' => 'devise/registrations#update', :as => 'registration'
  end
  get 'home/index'
  get 'home/error'
  get 'home/help'
  get 'home/contact'

  get '/restricted', to: 'home#restricted', as: :restricted

  get 'products/search'

  resources :settings, :except => [:new, :create, :destroy, :show]
  get 'products/quota_dashboard'
  resources :products  do
    member do
      get 'view_transactions_for' => 'products#transactions'
      get 'view_inventory_for' => 'products#inventory'
    end
  end
  resources :users
  resources :stocks  do
    member do
      get 'recalc' => 'stocks#recalc'
#      get 'view_stats_for' => 'stocks#stats'   #unused
    end
  end


end

app/models/setting.rb
class Setting < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  def self.get_value_for_name(name)
    setting=Setting.find_by_name(name)
    case(setting.kind)
    when 'String'
      setting.value
    when 'Integer'
      setting.value.to_i
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]
  before_action :authorize_action
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to settings_path, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:name, :value, :kind)
    end

    def user_not_authorized
      flash[:warning] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
    
    def authorize_action
      authorize Setting
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(setting) do |f| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :kind %>
    <%= f.text_field :kind %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.name %></td>
        <td><%= setting.value %></td>
        <td><%= setting.kind %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @setting.value %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @setting.kind %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>