config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #if logged in, root is home page
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  #otherwise root is login page
  root to: redirect('/users/sign_in')

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'registration/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'registration/:id' => 'devise/registrations#update', :as => 'registration'
  end
  get 'home/index'
  get 'home/error'
  get 'home/help'
  get 'home/contact'

  get '/restricted', to: 'home#restricted', as: :restricted

  get 'products/search'

  resources :settings, :except => [:new, :create, :destroy, :show]
  get 'products/quota_dashboard'
  resources :products  do
    member do
      get 'view_transactions_for' => 'products#transactions'
      get 'view_inventory_for' => 'products#inventory'
    end
  end
  resources :users
  resources :stocks  do
    member do
      get 'recalc' => 'stocks#recalc'
#      get 'view_stats_for' => 'stocks#stats'   #unused
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OTMES</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'OTMES', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%#= link_to 'Restricted', restricted_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Home', home_index_path %></li>
          <li><%= link_to 'Help', home_help_path %></li>
          <li><%= link_to 'Contact', home_contact_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Welcome <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              <% if(current_user.admin?) %>
                <li><%= link_to 'Users', users_path %></li>
                <li><%= link_to 'Settings', settings_path %></li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
      <br>
          <!---search--->
          <input id=searchstring>
          <input type=button value="Search" id=searchbutton>	
          <!--input type=button value="Search Receipt" id=receiptsearchbutton-->	
          <!---end search--->
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<div class="container">
  <div id="searchresult"></div>

  <%= yield %>
</div>

</body>
</html>
<script>
$("#productsearchbutton").click(function(event){
    var searchstring=$('#searchstring').val();
    if(searchstring.trim().length==0)return;
    var url="<%=request.protocol+request.host+':'+request.port.to_s%>";
    url=url+"/products/search"
    url=url+"?searchstring="+searchstring;
    url=url+"&transaction_id=<%=@transaction_id%>";
    url=url+"&transaction_type=<%=@transaction_type%>";
    $.ajax({
      url: url, 
      success: function(result){
 		    $("#searchresult").html(result);
      }})
  });
</script>